### ISSUE TITLE
pagination or infinite-scroll?

### ISSUE THREAD

**Issue by mountain** [covid2019memories/covid2019memories.org#2]
try pagination and  infinite-scroll on index page.

* infinite-scroll https://github.com/metafizzy/infinite-scroll
* flask-pagination https://pythonhosted.org/Flask-paginate/

infinite-scroll is more common on the mobile device.

**Comment by ZoomQuiet** [comment]
in mobile is more like infinite-scroll;
but in desktop, pagination is more nature?

**Comment by mountain** [comment]
this is issue can be solved this way ed2cb30c9d59d0334e470672c97a9197b09da02a
